config/routes.rb
Rails.application.routes.draw do
  resources :tr_contact_history do
    collection do
      get 'csv'
    end
  end
  get '/csv' => 'csv#create'
  get 'tr_contact_history/main'
  get 'top' => 'root#root'
  get '/main', to: 'tr_contact_history#main'
  get 'tr_contact_history/csv'
  post 'tr_contact_history' => 'tr_contact_history#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ms_hirise_staff.rb
class MsHiriseStaff < ApplicationRecord
  has_many :tr_contact_historys #userに対してtr_contact_historyは複数持つ

  def view_staffs
    '(' + self.staff_no + ')' + self.staff_name
  end

end

app/models/tr_contact_history.rb
class TrContactHistory < ApplicationRecord
  belongs_to :ms_hirise_staff, optional: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_controller.rb
class CsvController < ApplicationController
def create
  @csv = TrContactHistory.new
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def root
  end
end

app/controllers/tr_contact_history_controller.rb
require "date"
require 'active_support/all'
require 'mysql2'
require 'csv'

class TrContactHistoryController < ApplicationController
  def main #viewの行き先
    @today = Date.today.strftime('%Y年%m月%d日')
    @history = TrContactHistory.new
    @staffs = MsHiriseStaff.all
  end

  def create
    # byebug
    from = Time.now.at_beginning_of_day
    to   = from + 1.day
    tr_contact_history = TrContactHistory.new(tr_params)
    if TrContactHistory.where(created_at: from...to).where(tr_params).present?
      # 値を更新するメソッド
      tr_contact_history.assign_attributes({contact_datetime: Time.now, contact_registration_type: 2, created_at: Time.now, updated_at: Time.now})
      tr_contact_history.save
      flash[:success] = "退席完了"
     else
      tr_contact_history.assign_attributes({contact_datetime: Time.now, contact_registration_type: 1, created_at: Time.now, updated_at: Time.now})
      tr_contact_history.save
     flash[:notice] = "出席完了"
     end
    redirect_to '/main'
  end

      def csv
      #Mysql接続
      client = Mysql2::Client.new(
        host: "localhost",
        username: "root",
        password: '',
        database: "AM_app_development",
        :encoding => 'utf8',
        stream: true,
        cache_rows: false,
      )

      @results = client.query(
        "select 
          ms.staff_no, ms.staff_name, 
          DATE_FORMAT(contact_datetime,'%Y/%m/%d'),
          GROUP_CONCAT(TIME_FORMAT(tr.created_at, '%h時%i分'))
           from 
            ms_hirise_staffs as ms inner join tr_contact_histories as tr 
            on tr.ms_hirise_staff_id = ms.staff_no
             where
              tr.created_at
               in (select max(created_at) from tr_contact_histories
                group by 
                 contact_registration_type, tr_contact_histories.ms_hirise_staff_id)
                 group by
                  ms.staff_no, ms.staff_name, DATE_FORMAT(contact_datetime,'%Y/%m/%d')

       ")

      send_posts_csv(@results)
     # send_data render_to_string, filename: "出退勤管理シート.csv", type: :csv
      # results.each do |result|
       # puts result
      # end
        # CSV.open("tr_contact_histories.csv", "w") do |csv|
        # csv << results.fields
        # results.each do |row|
        #   csv << row.values
        # end
      # end
      # send_data(csv_data, filename: "tr_contact_history.csv")
      end

      def send_posts_csv(results)
        csv_data = CSV.generate(force_quotes: true, encoding:Encoding::SJIS) do |csv|
          header = %w(社員番号 社員名 出勤年月日 出勤時間 退勤時間)
          csv << header

          results.each do |result|
            csv << result.values
          end
        
      end
      send_data(csv_data, filename: "Timesheet.csv")
    end
  private
  def tr_params
      params.require(:tr_contact_history).permit(:ms_hirise_staff_id)
      # { ms_hirise_staff_id: params[:ms_hirise_staff_id]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_helper.rb
module CsvHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/tr_contact_history_helper.rb
module TrContactHistoryHelper
end

app/views/csv/create.html.erb
<!DOCTYPE html>

<html lang="ja">

  <head>
    <meta charset="utf-8">
    <link rel="stylesheets" href="csv.scss">
    <title>出退勤管理システム(Hirise)</title>
  </head>

  <body>
    <div class="header1">
        <%= image_tag 'image7.png', :size=>'150x70' %>
        <span style="font-size: 200%; vertical-align: 20px;">ハイライズ株式会社　　</span>
        <span style="font-size: 120%; vertical-align: 20px;">社内システム</span>
        <p style="float: right;">
        <script type="text/javascript">
            <!--

            var weeks = new Array('日','月','火','水','木','金','土');

            var now = new Date();

            var year = now.getYear(); // 年
            var month = now.getMonth() + 1; // 月
            var day = now.getDate(); // 日
            var week = weeks[ now.getDay() ]; // 曜日
            var hour = now.getHours(); // 時
            var min = now.getMinutes(); // 分
            var sec = now.getSeconds(); // 秒

            if(year < 2000) { year += 1900; }

            // 数値が1桁の場合、頭に0を付けて2桁で表示する指定
            if(month < 10) { month = "0" + month; }
            if(day < 10) { day = "0" + day; }
            if(hour < 10) { hour = "0" + hour; }
            if(min < 10) { min = "0" + min; }
            if(sec < 10) { sec = "0" + sec; }

            // 表示開始
            document.writeln('画面表示日時<br>');
            document.writeln(year + '-' + month + '-' + day + '<br>');
            document.writeln(hour + '時' + min + '分' + sec + '秒</b>');
            // 表示終了

            // -->
        </script>
      </p>
      </div>
      <div class="header2">
        
      </div>
      <div class="header3">
        <%= link_to '出退勤管理画面', '/main', class: 'class', method: :get %><br>
        <%= link_to '出退勤CSV出力', '/csv', class: 'class', method: :get %>
      </div>
      <div>
        <div class="main">
          <div>■社員名を選択し、連絡ボタンを押下してください</div><br>
          <%= form_for(@csv, url: {controller:'csv', action: 'create'}) do |f| %>
          <div style="margin-top: 8px; float: left;">♦︎ CSV出力年月： 　年　</div>
            <div class="cp02_ipselect cp_sl01" style="float: left;">
              <%= f.date_select :contact_datetime, {start_year: 2020, end_year: 2040, discard_month: true, discard_day: true, } %></div>
          <div style="margin: 8px 10px 0px 6px; float: left;">　月　</div>
            <div class="cp02_ipselect cp_sl01">
              <%= f.date_select :contact_datetime, {discard_year: true, use_month_numbers: true, discard_day: true, } %></div><br>
          <div style="margin-top: 8px; float: left;">♦︎ 出力フォルダ ： </div>
            <div class="cp_iptxt" style="float: left;">
              <input type="text" value="C:￥download" style="margin-left: 10px;"><%#= text_field_tag 'Directory', '', placeholder: "C:￥download", :size=>"90x30"%></dif>
          <% end %>
        </div><br>
        <%= form_tag tr_contact_history_csv_path(format: :csv), method: 'get', enforce_utf8: false do %><br>
        <button type="submit" class="btn-square02">CSV出力</button>
            <%#= submit_tag 'CSV出力' %>
          <% end %>
      </div>

      <div><%#= link_to "CSV出力", tr_contact_history_csv_path(format: :csv) %></div>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AMApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/root.html.erb
<h1>Root#root</h1>
<p>Find me in app/views/root/root.html.erb</p>
<p>テスト</p>

app/views/tr_contact_history/main.html.erb
<!DOCTYPE html>

<html lang="ja">

  <head>
    <meta charset="utf-8">
    <link rel="stylesheets" href="tr_contact_history.scss">
    <title>出退勤管理システム(Hirise)</title>
  </head>

    <body>
      <div class="header1">
        <%= image_tag 'image7.png', :size=>'150x70' %>
        <span style="font-size: 200%; vertical-align: 20px;">ハイライズ株式会社　　</span>
        <span style="font-size: 120%; vertical-align: 20px;">社内システム</span>
        <p style="float: right;">
        <script type="text/javascript">
            <!--

            var weeks = new Array('日','月','火','水','木','金','土');

            var now = new Date();

            var year = now.getYear(); // 年
            var month = now.getMonth() + 1; // 月
            var day = now.getDate(); // 日
            var week = weeks[ now.getDay() ]; // 曜日
            var hour = now.getHours(); // 時
            var min = now.getMinutes(); // 分
            var sec = now.getSeconds(); // 秒

            if(year < 2000) { year += 1900; }

            // 数値が1桁の場合、頭に0を付けて2桁で表示する指定
            if(month < 10) { month = "0" + month; }
            if(day < 10) { day = "0" + day; }
            if(hour < 10) { hour = "0" + hour; }
            if(min < 10) { min = "0" + min; }
            if(sec < 10) { sec = "0" + sec; }

            // 表示開始
            document.writeln('画面表示日時<br>');
            document.writeln(year + '-' + month + '-' + day + '<br>');
            document.writeln(hour + '時' + min + '分' + sec + '秒</b>');
            // 表示終了

            // -->
        </script>
      </p>
      </div>
      <div class="header2">
        
      </div>
      <div class="header3">
        <%= link_to '出退勤管理画面', '/main', class: 'class', method: :get %><br>
        <%= link_to '出退勤CSV出力', '/csv', class: 'class', method: :get %>
      </div>

      <div class="main">
        <div>■社員名を選択し、連絡ボタンを押下してください</div><br>
            <%= form_for(@history, url: {controller:'tr_contact_history', action: 'create'}) do |f| %>
              <div style="margin-top: 8px;">♦︎ 連絡年月日 ： 　<%= @today %></div><br>
              <div style="margin-top: 8px; float: left;">♦︎ 社員名　　 ： 　</div>
                <div class="cp_ipselect cp_sl01" style="float: left;">
                  <%= f.collection_select(:ms_hirise_staff_id, @staffs, :staff_no, :view_staffs) %>
                </div>
              <div style="clear: both;">
                <button type="f.submit" class="btn-square">連　絡</button>
              </div>
                <% if flash[:success] %>
              <div class="flash">
                <%= flash[:success] %>
              </div>
                <% end %>
                <% if flash[:notice] %>
              <div class="flash">
                <%= flash[:notice] %>
              </div>
                <% end %>
            <% end %>
      </div>

        <div>
          
        </div>
    </body>

</html>